services:
  ci_postgres:
    container_name: ci_postgres
    image: postgres:16.3
    restart: on-failure
    environment:
      POSTGRES_USER: "ci"
      POSTGRES_PASSWORD: "ci_pass"
      POSTGRES_DB: "ci_db"
    ports:
      - "5434:5432"
